# Generated by Django 2.2.12 on 2022-03-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdata',
            old_name='subcatgeory',
            new_name='subcategory',
        ),
    ]
