# Generated by Django 3.1 on 2022-05-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220516_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='corporate',
            name='corporate_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporates', to='app.user'),
        ),
    ]
